### ISSUE TITLE
変な文字列が表示されているので、消す

### ISSUE THREAD

**Issue by ogawaso** [tundes/my_app#6]
![2016-02-02 13 31 33](https://cloud.githubusercontent.com/assets/39783/12739937/a5dea636-c9b1-11e5-94ac-3974fee9e837.png)
- 画像の赤い部分の「s」の文字列

**Comment by tundes** [comment]
tabを2spaceへと変更した際に見つけたので消してしまいまして。

お忙しい中ありがとうございます。
ご確認よろしくお願いします。

**Comment by ogawaso** [comment]
修正確認しました
